### ISSUE TITLE
Yolox预测过程出错

### ISSUE THREAD

**Issue by kantkk** [alibaba/EasyCV#113]
我在使用Yolox教程里的预测过程，不过我没有自己训练，而是打算先用你们提供的模型参数，export之后再测试一下，预测过程报错：There are syntax errors in config file /home/xlh2/EasyCV2/.easycv_cache/epoch_300m_e_config.py: unmatched '}' (<unknown>, line 1)。经过调试，我发现错误出现在  easycv/predictors/detector.py   第90行：config_str = config_str[config_str.find('_base_'):]。在export过程中没有往pth文件里写入_base_,从而导致返回0索引值，进而返回无意义的”｛“。

**Comment by kantkk** [comment]
补充：在使用vitdet预测时报错'MaskRCNN is not in the model registry'，我不知道使用mmlab的maskrcnn如何加入到registry。

**Comment by Cathy0908** [comment]
> 补充：在使用vitdet预测时报错'MaskRCNN is not in the model registry'，我不知道使用mmlab的maskrcnn如何加入到registry。

mmdet模型的使用，请参考：[mmdet_models_usage_guide.md](https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/mmdet_models_usage_guide.md)

**Comment by kantkk** [comment]
> 

事实上我是在export过程中遇到的这个问题，在export过程中我的配置文件是写了mmdet那一部分的，但还是报错'MaskRCNN is not in the model registry'

**Comment by wenmengzhou** [comment]
> 

we have been looking at this problem, we will tell you as soon as we fix it

**Comment by Cathy0908** [comment]
> > 
> 
> 事实上我是在export过程中遇到的这个问题，在export过程中我的配置文件是写了mmdet那一部分的，但还是报错'MaskRCNN is not in the model registry'

We did not reproduce your error, in fact we have adapted mmdet in ``export.py`` and ``TorchViTDetPredictor``, please refer to:

https://github.com/alibaba/EasyCV/blob/master/tools/export.py?plain=1#L88


https://github.com/alibaba/EasyCV/blob/master/easycv/predictors/detector.py?plain=1#L297

**Comment by zouxinyi0625** [comment]
Thanks for pointing out the issue, and we have solved the problem of prediction error. See: https://github.com/alibaba/EasyCV/pull/125
