### ISSUE TITLE
difference between export model and original model ? 

### ISSUE THREAD

**Issue by zhangweida2080** [alibaba/EasyCV#129]
why should we have to export **model** before predicting , rather than use it directly ? 
为什么我们需要export 模型，然后再预测呢，为什么不直接预测呢 ？ 

yolox的例子中[https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%9B%BE%E5%83%8F%E6%A3%80%E6%B5%8BYoloX.ipynb]([])
 在导出模型之前，对nms阈值进行了修改， 如果用**vitdet**，请问需要怎么调整呢？需要吗，谢谢

**Comment by wenmengzhou** [comment]
we keep export interface to make the behaviour the same as exporting model to onnx/jit script,  if not set exporting to jit script, configuration info such as preprocess and postprocess will be written to pt file and used during inference.

vitdet follow the same workflow as yolox
