### ISSUE TITLE
Could easycv suuport batch inference?

### ISSUE THREAD

**Issue by tearscoco** [alibaba/EasyCV#142]
Thanks for your brilliant work!

I've looked at the inference demo of object detection but found batch inference is not supported yet.

Could you help support batch inference of detection models (ex. yolox)??

Appreciate!

**Comment by Cathy0908** [comment]
We have received your request and we will implement it as soon as possible.

**Comment by tearscoco** [comment]
Can I know when will this be ready??

**Comment by Cathy0908** [comment]
> Can I know when will this be ready??

in about 1-2 weeks
