### ISSUE TITLE
DAB-DETR mAP 42.52

### ISSUE THREAD

**Issue by KeiChiTse** [alibaba/EasyCV#162]
Thanks for your great work! I wonder if the **_mAP_ 42.52** of dab-detr is trained via the exact config file "configs/detection/dab_detr/dab_detr_r50_8x2_50e_coco.py"?
If so, I see that you use _**dropout = 0.0**_ in DABDetrTransformer instead of the default dropout value 0.1. Is there a **performance gain** by setting dropout value to **0.0**?

**Comment by tuofeilunhifi** [comment]
> 

We refer to the implementation of the source code, which defaults to 0.0. https://github.com/IDEA-opensource/DAB-DETR/blob/2306cfc8edbc359eb0b55b9859e1f1907409872a/main.py#L79

**Comment by KeiChiTse** [comment]
> .

Thanks for your reply!
