### ISSUE TITLE
Link error of yoloxs_pai_asff_tood3_8xb16_300e_coco config

### ISSUE THREAD

**Issue by RangeKing** [alibaba/EasyCV#164]
Something wrong with the config link, [yoloxs_pai_asff_tood3_8xb16_300e_coco](http://pai-vision-data-hz.oss-accelerate.aliyuncs.com/EasyCV/modelzoo/detection/yolox/yolox-pai/config/pai_yoloxs_tood3.py) in https://github.com/alibaba/EasyCV/blob/master/docs/source/model_zoo_det.md
![image](https://user-images.githubusercontent.com/27466624/186555218-c066060f-ee6b-42ee-8c53-2e76ff94d1cb.png)

**Comment by zouxinyi0625** [comment]
Sorry for the mistake, and we have update the config path. #166
