### ISSUE TITLE
So many grammar mistakes in README

### ISSUE THREAD

**Issue by lipond** [alibaba/EasyCV#167]
**_Listed here and noted by brackets "()"._**

Functionality & Extensibility

In addition to SSL, EasyCV also support(s) image classification, object detection, metric learning, and more area(s) will be supported in the future. Although convering different area(s), EasyCV decompose(s) the framework into different componets such as dataset, model (and) running hook, making it easy to add new compoenets and combining it with existing modules.

EasyCV provide(s) simple and comprehensive interface for inference. Additionaly, all models are supported on [PAI-EAS](https://help.aliyun.com/document_detail/113696.html), which can be easily deployed as online service and support automatic scaling and service monitoring.

Efficiency

EasyCV support(s) multi-gpu and multi worker training. EasyCV use(s) [DALI](https://github.com/NVIDIA/DALI) to accelerate data io and preprocessing process, and use(s) [TorchAccelerator](https://github.com/alibaba/EasyCV/tree/master/docs/source/tutorials/torchacc.md) and fp16 to accelerate training process. For inference optimization, EasyCV export(s) model using jit script, which can be optimized by [PAI-Blade](https://help.aliyun.com/document_detail/205134.html)

**Comment by wenmengzhou** [comment]
thanks, we will fix it
