### ISSUE TITLE
A all-in-one and clear feature extractor tutorial for users

### ISSUE THREAD

**Issue by HuaizhengZhang** [alibaba/EasyCV#190]
**Describe the feature**
Add a tutorial for feature extraction

**Motivation**
current tutorials include some feature extraction examples in SSL, but require users to spend a lot of time searching for. Also, some bugs in this examples

**Comment by wongts44** [comment]
+1, error in SSL export and inference, according to this guidance：https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%9B%BE%E5%83%8F%E8%87%AA%E7%9B%91%E7%9D%A3%E8%AE%AD%E7%BB%83-MAE.ipynb

**Comment by haiasd** [comment]
> +1, error in SSL export and inference, according to this guidance：https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%9B%BE%E5%83%8F%E8%87%AA%E7%9B%91%E7%9D%A3%E8%AE%AD%E7%BB%83-MAE.ipynb

Can you show error message？

**Comment by wongts44** [comment]
> > +1, error in SSL export and inference, according to this guidance：https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%9B%BE%E5%83%8F%E8%87%AA%E7%9B%91%E7%9D%A3%E8%AE%AD%E7%BB%83-MAE.ipynb
> 
> Can you show error message？

when came to last step, I followed this https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BBresnet50.ipynb to export and infer,
ValueError: dynamic_vit_base_p16 not in evtorch modelzoo!

**Comment by haiasd** [comment]
> > > +1, error in SSL export and inference, according to this guidance：https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%9B%BE%E5%83%8F%E8%87%AA%E7%9B%91%E7%9D%A3%E8%AE%AD%E7%BB%83-MAE.ipynb
> > 
> > 
> > Can you show error message？
> 
> when came to last step, I followed this https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BBresnet50.ipynb to export and infer, ValueError: dynamic_vit_base_p16 not in evtorch modelzoo!

Thanks for reply. We will fix it as soon as possible.
