### ISSUE TITLE
只有几张图,如何无监督学习?

### ISSUE THREAD

**Issue by monkeycc** [alibaba/EasyCV#227]
![1](https://user-images.githubusercontent.com/6490927/199871930-89f9463f-7825-420e-9fdd-5f9993de8893.png)

比如 只有 1-5张 完整 好的图

需要识别 有差异的 有缺的
但是又没有这些图

如何
完成这个需求？

**Comment by wenmengzhou** [comment]
这个恐怕暂时没法做到
