### ISSUE TITLE
What's the version of imagenet 21k provided in the repository?

### ISSUE THREAD

**Issue by touristourist** [alibaba/EasyCV#281]
Hi, I noticed that there exist two versions of imagenet 21k  from [Alibaba-MIIL/ImageNet21K](https://github.com/Alibaba-MIIL/ImageNet21K/blob/main/dataset_preprocessing/processing_instructions.md) which called fall 11 version and winter 11 version. So I wonder which version [this repository](https://github.com/alibaba/EasyCV/blob/master/docs/source/data_hub.md) provides? Thank you so much!

**Comment by tuofeilunhifi** [comment]
Fall 11 Version
