### ISSUE TITLE
BUG：'MSDA' is not defined

### ISSUE THREAD

**Issue by Alibaba-HZY** [alibaba/EasyCV#305]
when i do this gallery (https://pai.console.aliyun.com/?regionId=cn-shanghai&workspaceId=305319#/dsw-gallery-workspace/preview/deepLearning/cv/easycv_detection3d_bevformer)
executing this code 
`predictor = BEVFormerPredictor(
    model_path='../work_dirs/detection3d/bevformer/epoch_1.pth',
    config_file='../bevformer_base_r101_dcn_nuscenes.py',
)

inputs = mmcv.load('nuscenes_infos_temporal_val.pkl')['infos'][:1]` 
it will be report an error :
![image](https://user-images.githubusercontent.com/48040205/227892339-3dd1b636-8731-4424-8ed3-a7a9c078f55d.png)

I tried to use version 0.9 or recompile ( python setup.py build install)
but the problem was still stored

**Comment by Cathy0908** [comment]
MSDA will auto compile when running, maybe compile failed, you can refer to the following script to try to compile manually.

https://github.com/alibaba/EasyCV/blob/master/easycv/thirdparty/deformable_attention/functions/ms_deform_attn_func.py#L20

**Comment by Alibaba-HZY** [comment]
thank you  I forgot to restart kernel
