### ISSUE TITLE
使用YOLOX-PAI，将原始backbone替换成RepVGG后，预训练模型是否也要更改？

### ISSUE THREAD

**Issue by lunaWU628** [alibaba/EasyCV#309]
据我所知，更改了原始网络的backbone后，需要重新替换预训练模型，我将YOLOX的backbone(CSPNet)替换为RepVGG，但效果不好，是否是预训练模型的原因，如果要换预训练模型，请帖个模型下载链接或其他，感谢！

**Comment by zouxinyi0625** [comment]
YOLOX with RepVGG backbone can be found here:http://pai-vision-data-hz.oss-cn-zhangjiakou.aliyuncs.com/EasyCV/modelzoo/detection/yolox/yolox-pai/model/pai_yoloxs.pth.

For more pretrained models, you can refer to :  https://github.com/alibaba/EasyCV/blob/master/docs/source/model_zoo_det.md.

**Comment by lunaWU628** [comment]
Thank you very much!
