### ISSUE TITLE
Some scripts written in docs are not found

### ISSUE THREAD

**Issue by lipond** [alibaba/EasyCV#43]
Hi developers:

Thanks for your excellent project sharing to the community.

With a little pity, I found some faults.
For example, dist_train.sh in the following command is not found.
bash tools/dist_train.sh configs/classification/cifar10/swintiny_b64_5e_jpg.py $GPUS --fp16

Would you check and commit it anyway?

Thanks again.

**Comment by wenmengzhou** [comment]
thanks for your report, we will fix this right now
