### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'easycv.datasets.shared.pipelines.third_transforms_wrapper.RandomResizedCrop'>: attribute lookup RandomResizedCrop on easycv.datasets.shared.pipelines.third_transforms_wrapper failed

### ISSUE THREAD

**Issue by wuziheng** [alibaba/EasyCV#54]
I have an conda env with pip install -f requirements successfully and train moby success
then by replace configs/selfsup/dino/dino_deit_small_p16_8xb32_100e_jpg.py datalist and dataroot, training on a 8-V100 ,get failed with
<img width="893" alt="L1VzZXJzL3d6aC9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvaURpbmdUYWxrLzE3MjQxNzE5NF92Mi9JbWFnZUZpbGVzLzE2NTIxODYwNjEyMTlf5oiq5bGPMjAyMi0wNS0xMCDkuIvljYg4LjM0LjE3LnBuZw==" src="https://user-images.githubusercontent.com/11889926/167757592-f1d805f0-ffa0-481b-91da-19f949c6e865.png">

**Comment by Cathy0908** [comment]
We have fixed this bug, please refer to: https://github.com/alibaba/EasyCV/pull/31
