### ISSUE TITLE
ModuleNotFoundError: No module named 'sailfish'

### ISSUE THREAD

**Issue by zzoneee** [alibaba/EasyCV#83]
When I try to run the example of metric learning, I encountered the following error reports：
ModuleNotFoundError: No module named 'sailfish'

When I run the following command, error appears.
`CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/train.py configs/metric_learning/cub_resnet50_jpg.py --work_dir work_dirs/metric_learning/cub/r50 --launcher pytorch --fp16`

The URL of this example: https://github.com/alibaba/EasyCV/blob/master/docs/source/tutorials/EasyCV%E5%BA%A6%E9%87%8F%E5%AD%A6%E4%B9%A0resnet50.ipynb

**Comment by tuofeilunhifi** [comment]
pip install sailfish

**Comment by zzoneee** [comment]
> pip install sailfish

Thank you very much. Because my python version is 3.6, so I couldn't pip before.
